# Default Profile
[profile.default]
auto_detect_solc = true
optimizer = true
optimizer-runs = 1_000
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
cache_path  = 'cache_forge'
remappings = []

# Storage layout compatibility 
build_info = true
extra_output = ["storageLayout"]
# Grants access to solc
allow_paths = ['node_modules']

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
